---
title: "hwk_3"
author: "Andrew Mikolinski"
date: "2023-10-11"
output:
  pdf_document: default
  html_document: default
---

## Question 1 ##


A = matrix(data = runif(n = 1:500), nrow = 50, ncol = 10)
colnames(A) = paste("lake", 1:10, sep = "_")
set.seed(12) # to be reproducible


```{r}
set.seed(12) 

A = matrix(data = runif(n = 1:500), nrow = 50, ncol = 10)

colnames(A)= paste("lake",1:10,sep = "_")

column_means <- vector(mode = "numeric", length = ncol(A))

for (i in 1:ncol(A)) {

column_means[i] <- mean(A[[i]])
}

names(column_means) <- colnames(A)

column_means

y2<-numeric()

for (i in c(1:10)){

y1<-mean(A[,i])

y2<-c(y2,y1)

}

names(y2)<-colnames(A)

y2
```

## Question 2 ##
```{r}

X = c(1:27)
X
for (i in intersect(X, i <= 9)){
  x = X[c(1:9)]
  for (i in X) {
    y = X[c(10:18)]
    for (i in X) {
      z = X[c(19:27)]
      print(matrix(nrow = 3, ncol = 3, data=paste("",x,",",y,",",z,"")))
    }
  }
}

```


## Question 3 ##
```{r}
Fibonacci <- numeric(30)
Fibonacci[1] <- Fibonacci[2] <- 1
for (i in 3:30) 
  Fibonacci[i] <- Fibonacci[i - 2] + Fibonacci[i - 1]
  print(Fibonacci)
```

## Question 4&5 ##

```{r}
library("stringr")
top105 = readLines("http://www.textfiles.com/music/ktop100.txt")
top105 = top105[-c(1:10, 64, 65)]

top1052 <- str_extract_all(top105, pattern = "[^[:alpha:]-?&,()' ]", simplify = FALSE)
top1052[c(107)] <- top1052[c(107)-.3] 
top1052[c(98)] <- top1052[c(98) - 0.69]
top1052[c(29)] <- top1052[c(29)-0.3]
top1052[c(16)] <- top1052[c(16)-0.2]
top1052[c(9)] <- top1052[c(9)-0.3]
top1052 <- top1052[-c(108:111)]
top1052

top105 = readLines("http://www.textfiles.com/music/ktop100.txt")
top105 = top105[-c(1:10, 64, 65)]
top1053 <- str_extract_all(top105, pattern = "[^\\.[:alpha:]-?&,()' ]", simplify = FALSE)
top1053 <- top1053[-c(108:111)]
top1053[c(107)] <- top1053[c(107)-.3] 
top1053[c(98)] <- top1053[c(98) - 0.69]
top1053[c(29)] <- top1053[c(29)-0.3]
top1053[c(16)] <- top1053[c(16)-0.2]
top1053[c(9)] <- top1053[c(9)-0.3]
duplicated(top1053)
```




